### ISSUE TITLE
Storefront homepage throws error on fresh install, and products throw 404

### ISSUE THREAD

**Issue by tdh-store** [mirumee/saleor-storefront#1046]
### What I'm trying to achieve
A working Saleor install (homepage throws error but other pages such as account and 404 work)

### Steps to reproduce the problem
1.  Install Saleor core , saleor dashboard, and saleor storefront (all on master branch)
2.  Add a product to the dashboard
3.  Launch the storefront

### What I expected to happen
Working storefront homepage and product pages

### Screenshots
Homepage issue
![image](https://user-images.githubusercontent.com/84208428/118337874-595bf100-b4da-11eb-987f-f1e0e4727c43.png)
Search working but product leads to 404:
![image](https://user-images.githubusercontent.com/84208428/118338084-e99a3600-b4da-11eb-9575-5a76e75bb39a.png)
Account working:
![image](https://user-images.githubusercontent.com/84208428/118338263-501f5400-b4db-11eb-9283-8048d269c425.png)

If I swap to the 3.0 tag for storefront it throws this error on every page load:
error - ReferenceError: window is not defined
    at Object.<anonymous> (/PATH_TO_SALEOR_STOREFRONT/node_modules/braintree-web/lib/vendor/polyfill.js:3:51)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/PATH_TO_SALEOR_STOREFRONT/node_modules/braintree-web/lib/create-authorization-data.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/root/saleor-storefront2/node_modules/braintree-web/lib/add-metadata.js:3:31)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)

**System information**
Operating system: Freebsd
Browser: Firefox

**Comment by abdessalllam** [comment]
Try compose-stop then remove then build again.
