### ISSUE TITLE
Cant run codegen-sdk

### ISSUE THREAD

**Issue by mehrdad-shokri** [mirumee/saleor-storefront#1071]
### What I'm trying to achieve
run ``npm run codegen-sdk`` for codegen
### Steps to reproduce the problem
1. ``npm i``
2. ``npm run codegen-sdk``

### What I expected to happen
generate types from backend. Seems like ``src/@sdk`` is not existing  

**System information**
Operating system: Fedora 34 
Browser: Chrome
Node: 14
Npm: 7

**Comment by mehrdad-shokri** [comment]
Found out that ``apollo.config.js`` is located at root so chaning npm script to ``    "codegen-sdk": "apollo codegen:generate --target=typescript gqlTypes --config apollo.config.js --globalTypesFile src/@sdk/gqlTypes/globalTypes.ts"`` solved that problem for me. Now running codegen/codegen-sdk gives this error:  
```
Validation of GraphQL query document failed
    at Object.validateQueryDocument (/home/mehrdad/code/petshop/saleor-platform/saleor-storefront/node_modules/apollo-language-server/lib/errors/validation.js:39:38)
    at Object.generate [as default] (/home/mehrdad/code/petshop/saleor-platform/saleor-storefront/node_modules/apollo/lib/generate.js:23:18)
```
Related to [this](https://github.com/mirumee/saleor/issues/7601)?

**Comment by mehrdad-shokri** [comment]
I think ``codegen-sdk`` is related to ``@saleor/sdk`` codegen. so maybe instead of ``src/@sdk`` we should replace with ``@saleor/sdk``?
