### ISSUE TITLE
Little Issues on the pre release version

### ISSUE THREAD

**Issue by jayasth** [mirumee/saleor-storefront#1081]
### What I'm trying to achieve
I am testing saleor-storefront version 3.0.0-b.1 with current saleor  and saleor-dashboard 

### These are the issues I am facing:
1. If I have more than 3 product categories, only 3 of them shows up on the front page where it says "SHOP BY CATEGORY", I could not figure out how to fix this.
2. When run it in production mode with next server run:$ npm run build:start (these issues could not be reproduced when I run npm run start),  I am facing the following issues:
a. If I add the product (from the dashboard), it shows up on the category page, but does not show up in the front page FEATURED section, if the product is featured.
b. If I change the quantity of a product to 0, it still lets me add the product on the cart, but when I try to checkout it does not go to the next step (shipping).
c. I can see this error on console:

ApolloError: GraphQL error: At least one of arguments is required: 'id', 'slug'.
    at new ApolloError (/Users/myfolder/saleor-frontstore/node_modules/apollo-client/bundle.umd.js:92:26)
    at /Users/myfolder/saleor-frontstore/node_modules/apollo-client/bundle.umd.js:1588:34
    at /Users/myfolder/saleor-frontstore/node_modules/apollo-client/bundle.umd.js:2008:15
    at Set.forEach (<anonymous>)
    at /Users/myfolder/saleor-frontstore/node_modules/apollo-client/bundle.umd.js:2006:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/Users/myfolder/saleor-frontstore/node_modules/apollo-client/bundle.umd.js:2004:20)
    at /Users/myfolder/saleor-frontstore/node_modules/apollo-client/bundle.umd.js:2131:19
    at Object.next (/Users/myfolder/saleor-frontstore/node_modules/zen-observable/lib/Observable.js:308:23)
    at notifySubscription (/Users/myfolder/saleor-frontstore/node_modules/zen-observable/lib/Observable.js:130:18) {
  graphQLErrors: [
    {
      message: "At least one of arguments is required: 'id', 'slug'.",
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ],
  networkError: null,
  extraInfo: undefined

**Comment by albertphil** [comment]
Same here

**Comment by tmechsner** [comment]
Same here

**Comment by healthyl** [comment]
Same here
