### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by jiapei100** [mirumee/saleor-storefront#1140]
### What I'm trying to achieve
Successfully `pnpm run build`.

### Steps to reproduce the problem
1. `pnpm i`
2. `pnpm up --latest`

### What I expected to happen
The following ERR messages gone.

```console
   saleor-storefront git:(main) ✗ pnpm i
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
➜  saleor-storefront git:(main) ✗ pnpm run build

> saleor-site@3.0.0-a.0 build ~/saleor-storefront
> next build

warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://nextjs.org/docs/messages/react-version
info  - Loaded env from ~/saleor-storefront/.env.production
info  - Loaded env from ~/saleor-storefront/.env

> Build error occurred
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (~/saleor-storefront/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.11_3zhg573msb4eefp4jljvlczuiu/node_modules/fork-ts-checker-webpack-plugin/lib/issue/issue-webpack-error.js:11:51)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (~/saleor-storefront/node_modules/.pnpm/fork-ts-checker-webpack-plugin@7.2.11_3zhg573msb4eefp4jljvlczuiu/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:14:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
 ELIFECYCLE  Command failed with exit code 1.
➜  saleor-storefront git:(main) ✗ 
```

### Screenshots
N/A

**System information**
Operating system: Ubuntu 20.04
Browser: Chrome
Node: v16.15.0

Any suggestions?

Thank you ...

**Comment by jiapei100** [comment]
Sorry, my bad... Deprecated...
