### ISSUE TITLE
problem while running npm i

### ISSUE THREAD

**Issue by V1shishta** [mirumee/saleor-storefront#226]
`npm i`

gives the following error in the log files
```
23064 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...les","lib":"./src","t'

23064 verbose stack     at JSON.parse (<anonymous>)
23064 verbose stack     at parseJson (C:\Program Files\nodejs\n
ode_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)

23064 verbose stack     at consumeBody.call.then.buffer (C:\ProgramFiles\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)

23064 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)

23065 verbose cwd C:\Users\Vishishta\Desktop\saleor-storefront-master

23066 verbose Windows_NT 10.0.17134

23067 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramFiles\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"

23068 verbose node v10.11.0

23069 verbose npm  v6.4.1

23070 error Unexpected end of JSON input while parsing near '...les","lib":"./src","t'

23071 verbose exit [ 1, true ]
```
Please help

**Comment by piotrgrundas** [comment]
Node v?

**Comment by piotrgrundas** [comment]
I've just run `npm i`  using ur node version without any issues.
Could u try cleaning the cache and see if that helps? 
`npm cache clean --force`
