### ISSUE TITLE
Cannot list products of some categories (locally)

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-storefront#295]
Hi, in both chrome and firefox, I cannot access the groceries, accessories and apparel categories (e.g., /category/groceries/8/). I'm unsure how to debug this issue and where this is coming from.

I'm using the latest version from master, without any edit done to it. Let me know if you can reproduce it, or not and if possible, any instructions on how to debug the issue.

```
Uncaught Invariant Violation: StrictTypedQuery(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (http://127.0.0.1:3000/js/app.js:65745:15)
    at reconcileChildFibers (http://127.0.0.1:3000/js/app.js:79449:13)
    at reconcileChildren (http://127.0.0.1:3000/js/app.js:79768:28)
    at finishClassComponent (http://127.0.0.1:3000/js/app.js:80008:5)
    at updateClassComponent (http://127.0.0.1:3000/js/app.js:79954:10)
    at beginWork (http://127.0.0.1:3000/js/app.js:80772:16)
    at performUnitOfWork (http://127.0.0.1:3000/js/app.js:83510:12)
    at workLoop (http://127.0.0.1:3000/js/app.js:83550:24)
    at HTMLUnknownElement.callCallback (http://127.0.0.1:3000/js/app.js:65839:14)
    at Object.invokeGuardedCallbackDev (http://127.0.0.1:3000/js/app.js:65889:16)
invariant @ react-dom.development.js:55
reconcileChildFibers @ react-dom.development.js:13759
reconcileChildren @ react-dom.development.js:14078
finishClassComponent @ react-dom.development.js:14318
updateClassComponent @ react-dom.development.js:14264
beginWork @ react-dom.development.js:15082
performUnitOfWork @ react-dom.development.js:17820
workLoop @ react-dom.development.js:17860
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:17107
renderRoot @ react-dom.development.js:17979
performWorkOnRoot @ react-dom.development.js:18837
performWork @ react-dom.development.js:18749
performSyncWork @ react-dom.development.js:18723
requestWork @ react-dom.development.js:18592
scheduleWork @ react-dom.development.js:18401
scheduleRootUpdate @ react-dom.development.js:19069
updateContainerAtExpirationTime @ react-dom.development.js:19097
updateContainer @ react-dom.development.js:19154
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:19416
(anonymous) @ react-dom.development.js:19556
unbatchedUpdates @ react-dom.development.js:18952
legacyRenderSubtreeIntoContainer @ react-dom.development.js:19552
render @ react-dom.development.js:19613
(anonymous) @ index.tsx:72
fulfilled @ app.js:119644
Promise.then (async)
step @ app.js:119646
(anonymous) @ app.js:119647
./src/index.tsx.__awaiter @ app.js:119643
startApp @ index.tsx:62
./src/index.tsx @ index.tsx:130
__webpack_require__ @ bootstrap:19
0 @ globalTypes.ts:91
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
react-dom.development.js:15749 The above error occurred in the <StrictTypedQuery> component:
    in StrictTypedQuery
    in Unknown (created by NetworkStatus)
    in NetworkStatus
    in Unknown (created by Route)
    in Route
    in Switch
    in Unknown (created by App)
    in App (created by Route)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in CartProvider (created by Context.Consumer)
    in StrictTypedQuery
    in Unknown (created by StrictTypedQuery)
    in StrictTypedQuery
    in Unknown (created by Provider)
    in Provider (created by Context.Consumer)
    in UserProvider (created by extendedComponent)
    in extendedComponent (created by Context.Consumer)
    in Provider (created by Route)
    in Route (created by withRouter(Provider))
    in withRouter(Provider)
    in StrictTypedQuery
    in Unknown (created by ShopProvider)
    in ShopProvider
    in ApolloProvider
    in Router

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:15749
logError @ react-dom.development.js:15783
update.callback @ react-dom.development.js:16649
callCallback @ react-dom.development.js:11164
commitUpdateEffects @ react-dom.development.js:11203
commitUpdateQueue @ react-dom.development.js:11194
commitLifeCycles @ react-dom.development.js:16010
commitAllLifeCycles @ react-dom.development.js:17262
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:17458
completeRoot @ react-dom.development.js:18912
performWorkOnRoot @ react-dom.development.js:18841
performWork @ react-dom.development.js:18749
performSyncWork @ react-dom.development.js:18723
requestWork @ react-dom.development.js:18592
scheduleWork @ react-dom.development.js:18401
scheduleRootUpdate @ react-dom.development.js:19069
updateContainerAtExpirationTime @ react-dom.development.js:19097
updateContainer @ react-dom.development.js:19154
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:19416
(anonymous) @ react-dom.development.js:19556
unbatchedUpdates @ react-dom.development.js:18952
legacyRenderSubtreeIntoContainer @ react-dom.development.js:19552
render @ react-dom.development.js:19613
(anonymous) @ index.tsx:72
fulfilled @ app.js:119644
Promise.then (async)
step @ app.js:119646
(anonymous) @ app.js:119647
./src/index.tsx.__awaiter @ app.js:119643
startApp @ index.tsx:62
./src/index.tsx @ index.tsx:130
__webpack_require__ @ bootstrap:19
0 @ globalTypes.ts:91
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
react-dom.development.js:55 Uncaught (in promise) Invariant Violation: StrictTypedQuery(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at invariant (http://127.0.0.1:3000/js/app.js:65745:15)
    at reconcileChildFibers (http://127.0.0.1:3000/js/app.js:79449:13)
    at reconcileChildren (http://127.0.0.1:3000/js/app.js:79768:28)
    at finishClassComponent (http://127.0.0.1:3000/js/app.js:80008:5)
    at updateClassComponent (http://127.0.0.1:3000/js/app.js:79954:10)
    at beginWork (http://127.0.0.1:3000/js/app.js:80772:16)
    at performUnitOfWork (http://127.0.0.1:3000/js/app.js:83510:12)
    at workLoop (http://127.0.0.1:3000/js/app.js:83550:24)
    at renderRoot (http://127.0.0.1:3000/js/app.js:83636:7)
    at performWorkOnRoot (http://127.0.0.1:3000/js/app.js:84527:7)
```

**Comment by NyanKiyoshi** [comment]
Been solved from the visit of someone.
