### ISSUE TITLE
I can not run saleor-storefront in VPS,please help,thanks~

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor-storefront#647]
### What I'm trying to achieve
…

deploy saleor-storefront in VPS(production environment)

### Steps to reproduce the problem
1. package.json 162 line is:
   ` "start": "cross-env NODE_ENV=develop API_URI= http://106.14.24.151:8001/graphql/ webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly"`
2. cypress.json
{
  "baseUrl": "http://106.14.24.151:3001",
  "env": {
    "API_URI": "https://106.14.24.151:8001/graphql/"
  },
  "defaultCommandTimeout": 15000,
  "requestTimeout": 15000,
  "viewportWidth": 1400,
  "viewportHeight": 660,
  "projectId": "ftxg4w"
}

3.
cnpm i
cnpm start &

and get:
(python3.6) root@iZuf62cvmxv23irc7lrcobZ:~/saleor_rawstone/saleor-storefront#  cnpm start

> saleor-site@0.7.0 start /root/saleor_rawstone/saleor-storefront
> cross-env NODE_ENV=develop API_URI= http://106.14.24.151:8001/graphql/ webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn http://106.14.24.151:8001/graphql/ ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saleor-site@0.7.0 start: `cross-env NODE_ENV=develop API_URI= http://106.14.24.151:8001/graphql/ webpack-dev-server --history-api-fallback --watch --port 3000 --mode development --hotOnly`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saleor-site@0.7.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-13T05_40_15_796Z-debug.log

I guess my configuration is wrong,
could you tell me how to modify it?
Thanks~!

### What I expected to happen
…

### Screenshots

**System information**
Operating system: 
Ubuntu18.04
Python3.6

**Comment by appleyuchi** [comment]
solution:
export API_URI="XXXX:port"
npm start
