### ISSUE TITLE
graphql_jwt.exceptions.JSONWebTokenError: User is disabled

### ISSUE THREAD

**Issue by appleyuchi** [mirumee/saleor-storefront#648]
### What I'm trying to achieve
…
I want to register my website 

### Steps to reproduce the problem
1. visit  IP:port after I deploy saleor-storefront,saleor and saleor-dashboard
2. input email and password and click register,then get error log:
ERROR saleor.graphql.errors.unhandled A query failed unexpectedly [PID:32039:Thread-32]
Traceback (most recent call last):
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/root/saleor_rawstone/saleor/saleor/graphql/middleware.py", line 60, in service_account_middleware
    return next(root, info, **kwargs)
  File "/root/saleor_rawstone/saleor/saleor/graphql/middleware.py", line 22, in resolve
    return super().resolve(next, root, info, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/middleware.py", line 72, in resolve
    user = authenticate(request=context, **kwargs)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/backends.py", line 14, in authenticate
    return get_user_by_token(token, request)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/shortcuts.py", line 21, in get_user_by_token
    return get_user_by_payload(payload)
  File "/root/.virtualenvs/python3.6/lib/python3.6/site-packages/graphql_jwt/utils.py", line 113, in get_user_by_payload
    raise exceptions.JSONWebTokenError(_('User is disabled'))
graphql_jwt.exceptions.JSONWebTokenError: User is disabled

I have checked 106.14.24.151:8001/graphql,
it seems ok.

could you help me solve it?
Thanks.

### What I expected to happen
…

### Screenshots

![报错](https://user-images.githubusercontent.com/27613483/76597308-164f6800-653b-11ea-83d4-8f9b387c0aac.png)

**System information**
Operating system: 
Browser:

**Comment by appleyuchi** [comment]
The second quesition in this picture is:
I think localhost:3000 need to be configured in webpack.config.js
but I have little knowledge about this.
could you tell me how to modify it?
Thanks.

**Comment by appleyuchi** [comment]
After I reconstruct the posgreSQL database ,this problem disapppeared.

**Comment by PiotrLaszczyk** [comment]
I faced same issue today... its possible to reproduce

1) I was logged-in as user
2) Then next day I open browser and I was still logged in
3) After refreshing: from user pov pictures were not loaded and 404 display after clicking in links
saleor logs shows same error as in subject

To fix: Logout and login 

But typical user will be totally confused... looks like token is not refreshed/expired

**Comment by orzechdev** [comment]
@PiotrLaszczyk we have fixed mentioned problem in https://github.com/mirumee/saleor-storefront/pull/696, user should be logged out now, when token is expired
